// Screen-specific questions, with no named encounters or prescribed builds.
export function decisionFocus(state) {
 if(state.state_type==='crystal_sphere')return {name:'Divination',instructions:{move:'Choose a concrete tile to reveal with the current tool, or finish when appropriate. Switching tools reveals nothing and earns nothing. Switch only if it enables a specific better reveal, then execute that reveal on the next observation; do not alternate tools endlessly. Hidden cells have unknown contents; never infer rewards from coordinates.',resources:'Compare revealing a tile with finishing using the supplied rules and remaining divinations. A tool switch alone makes no progress; select it only to enable a concrete next reveal.'},review:'Check that the choice advances divination rather than reversing a tool selection. Choose among all supplied actions; hidden rewards are unknown.'};
 if(state.state_type==='hand_select')return {
  name:'Card selection',instructions:{survival:'For a replacement selection, compare confirming the current set with replacing unusable cards to find defense or a useful draw trigger. Compute current incoming damage minus block against HP. A card-play limit does not itself prohibit drawing or passive on-draw effects; check the visible rules separately. Do not assume any particular draw.',synergy:'Read visible on-draw powers and card-play restrictions separately. Replacement can trigger automatic plays even when ordinary hand plays are blocked, if the supplied rules allow it; treat uncertain interactions as uncertain. Compare this with keeping cards for later.',resources:'Count selected cards. Confirming zero replacements draws zero cards and wastes a redraw effect. Compare each unwanted or unaffordable card against retaining it, using remaining energy and visible triggers. Keep confirm available but require a concrete reason to replace nothing.',move:'Follow the actual selection prompt. For replacing any number of cards, compare selecting another unwanted card against confirming the current set. Confirm being available does not mean selection is complete. Consider remaining energy, card-play restrictions and which cards are useful to retain. Do not select useful cards merely to avoid an empty choice.'},review:'Check the selected cards and selection prompt before confirming. If nothing is selected, assess whether that would waste the effect.'
 };
 if (state.state_type==='rest_site') return {
  name:'Campfire', instructions:{
   move:'Compare actual healing capped by missing HP against permanently upgrading a specific useful card. Read the rest amount from the option and subtract current HP from max HP: do not value overhealing. Use current deck, recent fights and visible upcoming risks. Choose only an offered action.',
   survival:'Which campfire action best improves survival across the remaining run? Compare healing now against damage prevented or fights shortened by an upgrade. Do not automatically rest merely because HP is below maximum; do not upgrade when healing is necessary.',
   synergy:'Identify the current deck bottleneck: reliable damage, defense, draw, energy or scaling. Which offered campfire action best addresses it? For smithing, consider specific current cards. Do not invent exact upgraded card text that has not been supplied; reassess when the selection screen exposes upgrade details.',
   resources:'Compare effective healing with the lasting value of an upgrade and future opportunities actually visible. Consider how often the card is drawn and played. Do not assume another rest site will appear.'
  }, review:'Challenge a rest choice when much of its nominal healing would be wasted. Challenge an upgrade choice when current HP cannot support visible upcoming fights. Ground both in actual deck and observed damage, not a fixed HP threshold.'
 };
 if (state.state_type==='map') return {
  name:'Route', instructions:{
   move:'Use spending_routes to compare reachable shops and the forced fights before them. With substantial unspent gold, evaluate converting it into useful purchases before the boss, balanced against HP and route danger. Do not assume unknown shop inventory or prefer a shop regardless of safety. Choose the route with the best chance of completing the run. Compare current HP, potions, deck readiness and recent damage taken with the visible next rooms and their leads_to connections. Account for forced fights before healing or shopping. Do not treat a rest site beyond an elite as healing available before that elite. Do not invent unseen map information.',
   survival:'Which route best balances survival and improving the run? Check recent HP losses and whether the deck can sustain another difficult fight. Compare paths that avoid an elite when resources are depleted; avoid blanket rules that all elites are good or bad.',
   resources:'Compare visible opportunities for healing, upgrades, spending gold and earning rewards. Evaluate whether current HP and potions are enough to reach those opportunities, including fights forced by each branch.'
  }, review:'Audit the route through visible leads_to rooms before committing. A safe-looking next room may force a dangerous elite afterward. Check current health and recent fight losses against the alternative branch.'
 };
 if (['shop','fake_merchant'].includes(state.state_type)) return {
  name:'Merchant',
  instructions:{
   move:'Choose the best next purchase or leave. Compare relics, cards, potions and removal at their actual prices against retaining gold. Consider combinations of purchases within the current budget: buying one item can prevent another. Only one purchase executes before observing again. Leaving ends this shopping opportunity.',
   encounter:'Which available purchase or decision to leave best prepares this deck for upcoming fights? Use current weaknesses and observed encounter difficulties, plus only map or boss information actually supplied. Do not invent future shops, rewards or enemy phases.',
   synergy:'Compare the marginal benefit of each relic, card and removal for the current deck and energy. Relics can improve many future turns without adding cards to the draw pile. Identify actual interactions from the supplied rules. Removal can improve consistency; skipping weak cards does not imply skipping useful relics. Which candidate improves the deck most for its cost?',
   survival:'Which purchase or decision to leave most improves the chance of surviving the remaining run? Weigh current HP, defensive consistency, damage output and usable potions. Consider immediate protection and lasting benefits, including ending dangerous fights sooner.',
   pressure:'Which candidate best fixes a demonstrated weakness or improves reliable damage and scaling? Compare benefits that matter soon with setup costs and remaining opportunities to use them. A cheap card is not automatically better value than a relic or removal.',
   resources:'Allocate the current gold across the visible inventory. Compare affordable combinations of relics, cards, potions and removal and select the first purchase of the best allocation, or leave if saving is better. Account for gold remaining and potion capacity. Gold does not help in combat until spent; saving needs a concrete opportunity cost, not a blanket preference to conserve. Do not invent a future merchant.'
  },
  review:'Before choosing leave, challenge it against the strongest affordable purchase and purchase combination. Does saving the gold actually improve the remaining run more? Before buying, check whether it crowds out a more useful item, duplicates an already solved need, or adds an inconsistent card. Keep leaving available when purchases are poor value; do not buy merely to spend gold.'
 };
 if (['boss','elite'].includes(state.state_type)) return {
  name:state.state_type === 'boss' ? 'Boss' : 'Elite',
  instructions:{
   encounter:'Read every living enemy power, intent and condition from the visible state. Infer what triggers buffs, retaliation, summons, damage limits or stuns only when supported by those rules or observations. Which candidate best handles these mechanics? Compare recent rounds and the unfinished plan; distinguish observed patterns from uncertain future behavior. Do not assume unseen phases or future intents.',
   pressure:'Which candidate creates a credible path to winning this encounter? Compare damage, setup payoff, focus fire and visible thresholds across the fight. Use observed HP and Strength trends to detect a losing damage race. Setup must repay its immediate energy and survival cost; do not repeatedly set up or defend without progress. Unknown future draws and intents remain uncertain.',
   resources:'Which candidate uses energy, cards and potions best for this boss or elite? Compare using a potion now to its specific later value, including preventing damage, enabling setup, a kill or a visible stun. Saving consumables is not useful if it loses this encounter. Before a redraw potion, identify useful replacements and whether remaining energy and card-play restrictions allow benefiting from them. An empty replacement wastes the potion. Check card order and interactions before consuming resources; do not assume unseen draws.'
  },
  review:'Audit the chosen line against enemy powers and trigger timing, focus target, visible kill or stun thresholds, and potion alternatives. Is it merely surviving this turn while falling further behind? Compare a credible damage or setup line against defense using recent progress. Short-prefix forecasts are not complete turns: consider remaining energy and cards, and do not penalize a prefix as though ending immediately were mandatory. Do not fabricate unseen phases or exact future turns.'
 };
 return {name:'General',instructions:{},review:''};
}
